version: '1'
services:
  app:
    container_name: appmascotas
    ports:
    - "5000:5000"
    build: .
    restart: unless-stopped
    links:
    - mymongodb
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules

  mymongodb:
    container_name: mymongodatebase
    image: mongo
    ports:
    - "27018:27017"
    restart: unless-stopped
    volumes:
    - ../data:/data/db